//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyInvitation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int foodId { get; set; }
        public int foodTypeId { get; set; }
        public string foodName { get; set; }
        public string ImageFileName { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual FoodType FoodType { get; set; }
    }
}
