//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyInvitation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodType
    {
        public FoodType()
        {
            this.Foods = new HashSet<Food>();
        }
    
        public int FoodTypeId { get; set; }
        public string FoodTypeName { get; set; }
    
        public virtual ICollection<Food> Foods { get; set; }
    }
}
