//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyInvitation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GuestResponse
    {
        public GuestResponse()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int Id { get; set; }

         [Required(ErrorMessage="Please enter your first name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage="Please enter your last name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please specify whether you will attend")]
        public bool? WillAttend { get; set; }

        [Required(ErrorMessage = "Please enter your phone number")]
        public string TelephoneNumber { get; set; }

         [Required(ErrorMessage = "Please enter your email address")]
         [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Please enter a valid email address")]
        public string Address { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
